### ISSUE TITLE
No usage information

### ISSUE THREAD

**Issue by nico202** [imfly/ember-cli-fullPagejs#2]
The only info I could find is from issue #1 

`{{#full-page elementId="fullpage"}}
    your code
{{/full-page}}`
Maybe this (and oher information if needed) should be on the readme
thanks

**Comment by imfly** [comment]
Yes，it seems that I should improve it. :smile:

**Comment by nico202** [comment]
Still an ember newbie here, took 15 minutes to find out how to customize it (like didRender=model)

Il 15 agosto 2016 15:08:25 CEST, imfly notifications@github.com ha scritto:

> Yes，it seems that I should improve it. :smile: 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/imfly/ember-cli-fullPagejs/issues/2#issuecomment-239797280

## 

Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by imfly** [comment]
@nico202 Sorry, I‘m so lazy. I’ll improve it and make it eazier to use recently.

**Comment by imfly** [comment]
Docs was added. Please test it .
