### ISSUE TITLE
This Bower version is deprecated...

### ISSUE THREAD

**Issue by yawen0802** [imfly/ember-cli-fullPagejs#4]
Could you please update it by using <code>npm install -g bower</code>. The new registry address is https://registry.bower.io  Thanks!

**Comment by imfly** [comment]
The message tells you that you may update it by yourself on your local pc 😢

**Comment by yawen0802** [comment]
Hi! Thank you for the introduction. I have updated my local bower version and my .bowerrc file is using <code>
{
  "registry": "https://registry.bower.io"
}</code> but I am having the same error message after I installed the add on... I will dig a little deeper :)

**Comment by imfly** [comment]
Bower is installed successfully? What do u get if type `bower -v`?

**Comment by yawen0802** [comment]
1.8.4
